// <auto-generated/>
using System.Runtime.InteropServices;

namespace MDBX.Native.Types;

/// <summary>
/// Флаги проверки целостности базы данных.
/// </summary>
/// <remarks>
/// Значения соответствуют перечислению MDBX_chk_flags_t из заголовочного файла mdbx.h.
/// Могут быть объединены с помощью битовых операций.
/// </remarks>
[Flags]
public enum MdbxChkFlags : int
{
    /// <summary>
    /// Режим проверки по умолчанию, включая read-only режим.
    /// </summary>
    MDBX_CHK_DEFAULTS = 0,

    /// <summary>
    /// Проверка в read-write режиме с блокировкой и приостановкой записных транзакций.
    /// </summary>
    MDBX_CHK_READWRITE = 1,

    /// <summary>
    /// Пропустить обход дерева страниц.
    /// </summary>
    MDBX_CHK_SKIP_BTREE_TRAVERSAL = 2,

    /// <summary>
    /// Пропустить итерацию и просмотр записей ключ-значение.
    /// </summary>
    MDBX_CHK_SKIP_KV_TRAVERSAL = 4,

    /// <summary>
    /// Игнорировать порядок ключей и значений.
    /// Необходимо при проверке баз данных с нестандартными функциями сравнения.
    /// </summary>
    MDBX_CHK_IGNORE_ORDER = 8,
}

/// <summary>
/// Уровни логирования и детализации информации, передаваемые через
/// функции обратного вызова во время проверки целостности базы данных.
/// </summary>
/// <remarks>
/// Значения соответствуют перечислению MDBX_chk_severity_t из заголовочного файла mdbx.h.
/// </remarks>
public enum MdbxChkSeverity : uint
{
    /// <summary>
    /// Сдвиг приоритета для определения категории severitу.
    /// </summary>
    MDBX_chk_severity_prio_shift = 4,

    /// <summary>
    /// Маска для извлечения категории severity.
    /// </summary>
    MDBX_chk_severity_kind_mask = 0xF,

    /// <summary>
    /// Фатальная ошибка.
    /// </summary>
    MDBX_chk_fatal = 0x00,

    /// <summary>
    /// Ошибка.
    /// </summary>
    MDBX_chk_error = 0x11,

    /// <summary>
    /// Предупреждение.
    /// </summary>
    MDBX_chk_warning = 0x22,

    /// <summary>
    /// Уведомление.
    /// </summary>
    MDBX_chk_notice = 0x33,

    /// <summary>
    /// Результат проверки.
    /// </summary>
    MDBX_chk_result = 0x44,

    /// <summary>
    /// Разрешение проблемы.
    /// </summary>
    MDBX_chk_resolution = 0x55,

    /// <summary>
    /// Обработка.
    /// </summary>
    MDBX_chk_processing = 0x56,

    /// <summary>
    /// Информационное сообщение.
    /// </summary>
    MDBX_chk_info = 0x67,

    /// <summary>
    /// Подробное логирование.
    /// </summary>
    MDBX_chk_verbose = 0x78,

    /// <summary>
    /// Детали.
    /// </summary>
    MDBX_chk_details = 0x89,

    /// <summary>
    /// Дополнительная детализация.
    /// </summary>
    MDBX_chk_extra = 0x9A,
}

/// <summary>
/// Этапы проверки, сообщаемые через функции обратного вызова
/// во время проверки целостности базы данных.
/// </summary>
/// <remarks>
/// Значения соответствуют перечислению MDBX_chk_stage_t из заголовочного файла mdbx.h.
/// </remarks>
public enum MdbxChkStage : int
{
    /// <summary>
    /// Нет этапа.
    /// </summary>
    MDBX_chk_none = 0,

    /// <summary>
    /// Инициализация.
    /// </summary>
    MDBX_chk_init = 1,

    /// <summary>
    /// Блокировка.
    /// </summary>
    MDBX_chk_lock = 2,

    /// <summary>
    /// Проверка метаданных.
    /// </summary>
    MDBX_chk_meta = 3,

    /// <summary>
    /// Обход дерева.
    /// </summary>
    MDBX_chk_tree = 4,

    /// <summary>
    /// Проверка сборщика мусора.
    /// </summary>
    MDBX_chk_gc = 5,

    /// <summary>
    /// Проверка пространства.
    /// </summary>
    MDBX_chk_space = 6,

    /// <summary>
    /// Проверка MainDB.
    /// </summary>
    MDBX_chk_maindb = 7,

    /// <summary>
    /// Проверка таблиц.
    /// </summary>
    MDBX_chk_tables = 8,

    /// <summary>
    /// Завершение.
    /// </summary>
    MDBX_chk_conclude = 9,

    /// <summary>
    /// Снятие блокировки.
    /// </summary>
    MDBX_chk_unlock = 10,

    /// <summary>
    /// Финализация.
    /// </summary>
    MDBX_chk_finalize = 11,
}

/// <summary>
/// Виртуальная строка отчета, генерируемого во время проверки целостности базы данных.
/// </summary>
/// <remarks>
/// Соответствует структуре MDBX_chk_line_t из заголовочного файла mdbx.h.
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct MdbxChkLine
{
    /// <summary>
    /// Указатель на контекст проверки.
    /// </summary>
    public MdbxChkContext* Context;

    /// <summary>
    /// Уровень серьезности вывода.
    /// </summary>   
    public byte Severity;

    /// <summary>
    /// Глубина вложенности области.
    /// </summary>
    public byte ScopeDepth;

    /// <summary>
    /// Флаг пустой строки.
    /// </summary>
    public byte Empty;

    /// <summary>
    /// Указатель на начало строки вывода.
    /// </summary>
    public byte* Begin;

    /// <summary>
    /// Указатель на конец строки вывода.
    /// </summary>
    public byte* End;

    /// <summary>
    /// Указатель на текущую позицию вывода.
    /// </summary>
    public byte* Out;
}

/// <summary>
/// Проблема, обнаруженная во время проверки целостности базы данных.
/// </summary>
/// <remarks>
/// Соответствует структуре MDBX_chk_issue_t из заголовочного файла mdbx.h.
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct MdbxChkIssue
{
    /// <summary>
    /// Указатель на следующую проблему в списке.
    /// </summary>
    public MdbxChkIssue* Next;

    /// <summary>
    /// Количество вхождений проблемы.
    /// </summary>
    public nuint Count;

    /// <summary>
    /// Заголовок проблемы.
    /// </summary>
    public byte* Caption;
}

/// <summary>
/// Иерархический контекст во время проверки целостности базы данных.
/// </summary>
/// <remarks>
/// Соответствует структуре MDBX_chk_scope_t из заголовочного файла mdbx.h.
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct MdbxChkScope
{
    /// <summary>
    /// Список проблем, обнаруженных в данной области.
    /// </summary>
    public MdbxChkIssue* Issues;

    /// <summary>
    /// Внутренние данные (непрозрачный указатель).
    /// </summary>
    public void* Internal;

    /// <summary>
    /// Объект, связанный с этой областью.
    /// </summary>
    public void* Object;

    /// <summary>
    /// Этап проверки.
    /// </summary>
    public MdbxChkStage Stage;

    /// <summary>
    /// Уровень детализации (verbosity).
    /// </summary>
    public MdbxChkSeverity Verbosity;

    /// <summary>
    /// Подсчет проблем в этой области.
    /// </summary>
    public nuint SubtotalIssues;

    /// <summary>
    /// Пользовательские данные (union: ptr/number).
    /// </summary>
    public nint UsrZ;

    /// <summary>
    /// Пользовательские данные (union: ptr/number).
    /// </summary>
    public nint UsrV;

    /// <summary>
    /// Пользовательские данные (union: ptr/number).
    /// </summary>
    public nint UsrO;
}

/// <summary>
/// Неизменяемый тип для связывания дополнительных данных, связанных с определенной
/// таблицей ключ-значение во время проверки целостности базы данных.
/// </summary>
/// <remarks>
/// Соответствует типу MDBX_chk_user_table_cookie_t из заголовочного файла mdbx.h.
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public struct MdbxChkUserTableCookie
{
}

/// <summary>
/// Гистограмма для проверки целостности базы данных (управляемая версия для использования вне unsafe контекста).
/// Осуществляет сопоставление с нативной структурой MDBX_chk_histogram.
/// Используует фиксированный буфер для массива диапазонов, что позволяет
/// использовать указатели на структуры, содержащие эту гистограмму.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct MdbxChkHistogramData
{
    /// <summary>
    /// Размер одного диапазона гистограммы в байтах (4 * sizeof(nuint) = 32 на x64).
    /// </summary>
    public const int RangeSize = 32;

    /// <summary>
    /// Общее количество элементов.
    /// </summary>
    public nuint Amount;

    /// <summary>
    /// Количество интервалов.
    /// </summary>
    public nuint Count;

    /// <summary>
    /// Количество элементов &lt;= 1.
    /// </summary>
    public nuint Le1Amount;

    /// <summary>
    /// Количество интервалов &lt;= 1.
    /// </summary>
    public nuint Le1Count;

    /// <summary>
    /// Диапазоны гистограммы (9 штук), как фиксированный буфер байт.
    /// </summary>
    public fixed byte Ranges[9 * RangeSize];
}

/// <summary>
/// Информация о таблице ключ-значение во время проверки целостности базы данных.
/// </summary>
/// <remarks>
/// Соответствует структуре MDBX_chk_table_t из заголовочного файла mdbx.h.
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct MdbxChkTable
{
    /// <summary>
    /// cookie для связывания дополнительных данных.
    /// </summary>
    public MdbxChkUserTableCookie* Cookie;

    /// <summary>
    /// Имя таблицы.
    /// </summary>
    public MDBX_val Name;

    /// <summary>
    /// Флаги таблицы.
    /// </summary>
    public uint Flags;

    /// <summary>
    /// Идентификатор таблицы.
    /// </summary>
    public int Id;

    /// <summary>
    /// Объем полезной нагрузки в байтах.
    /// </summary>
    public nuint PayloadBytes;

    /// <summary>
    /// Потерянные байты.
    /// </summary>
    public nuint LostBytes;

    /// <summary>
    /// Статистика страниц.
    /// </summary>
    public MdbxChkTablePages Pages;

    /// <summary>
    /// Гистограммы.
    /// </summary>
    public MdbxChkTableHistograms Histogram;
}

/// <summary>
/// Псевдоним для MainDB: ((void*)((ptrdiff_t)0)).
/// </summary>
public static class MdbxChkMain { }

/// <summary>
/// Псевдоним для GarbageCollectorDB: ((void*)((ptrdiff_t)-1)).
/// </summary>
public static class MdbxChkGc { }

/// <summary>
/// Псевдоним для MetaPages: ((void*)((ptrdiff_t)-2)).
/// </summary>
public static class MdbxChkMeta { }

/// <summary>
/// Статистика страниц таблицы.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public struct MdbxChkTablePages
{
    /// <summary>
    /// Общее количество страниц.
    /// </summary>
    public nuint All;

    /// <summary>
    /// Количество пустых страниц.
    /// </summary>
    public nuint Empty;

    /// <summary>
    /// Количество сломанных страниц.
    /// </summary>
    public nuint Broken;

    /// <summary>
    /// Количество ветвящих страниц.
    /// </summary>
    public nuint Branch;

    /// <summary>
    /// Количество листовых страниц.
    /// </summary>
    public nuint Leaf;

    /// <summary>
    /// Количество вложенных ветвящих страниц.
    /// </summary>
    public nuint NestedBranch;

    /// <summary>
    /// Количество вложенных листовых страниц.
    /// </summary>
    public nuint NestedLeaf;

    /// <summary>
    /// Количество вложенных сублистовых страниц.
    /// </summary>
    public nuint NestedSubleaf;
}

/// <summary>
/// Гистограммы таблицы.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public struct MdbxChkTableHistograms
{
    /// <summary>
    /// Гистограмма высоты дерева.
    /// </summary>
    public MdbxChkHistogramData Height;

    /// <summary>
    /// Гистограмма длины больших/переполненных страниц.
    /// </summary>
    public MdbxChkHistogramData LargePages;

    /// <summary>
    /// Гистограмма высоты вложенных деревьев или длины span для GC.
    /// </summary>
    public MdbxChkHistogramData NestedHeightOrGcSpanLength;

    /// <summary>
    /// Гистограмма длин ключей.
    /// </summary>
    public MdbxChkHistogramData KeyLen;

    /// <summary>
    /// Гистограмма длин значений.
    /// </summary>
    public MdbxChkHistogramData ValLen;

    /// <summary>
    /// Гистограмма количества многозначных записей.
    /// </summary>
    public MdbxChkHistogramData Multival;

    /// <summary>
    /// Гистограмма заполнения ветвящих и листовых страниц в процентах.
    /// </summary>
    public MdbxChkHistogramData TreeDensity;

    /// <summary>
    /// Гистограмма заполнения вложенных деревьев ветвящих и листовых страниц в процентах.
    /// </summary>
    public MdbxChkHistogramData LargeOrNestedDensity;

    /// <summary>
    /// Гистограмма возраста страниц.
    /// </summary>
    public MdbxChkHistogramData PageAge;

    /// <summary>
    /// Гистограмма используемых pgno.
    /// </summary>
    public MdbxChkHistogramData Pgno;
}

/// <summary>
/// Контекст проверки целостности базы данных.
/// </summary>
/// <remarks>
/// Соответствует структуре MDBX_chk_context_t из заголовочного файла mdbx.h.
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct MdbxChkContext
{
    /// <summary>
    /// Внутренние данные (непрозрачный указатель).
    /// </summary>
    public void* Internal;

    /// <summary>
    /// Окружение.
    /// </summary>
    public MDBX_env* Env;

    /// <summary>
    /// Транзакция.
    /// </summary>
    public MDBX_txn* Txn;

    /// <summary>
    /// Текущая область.
    /// </summary>
    public MdbxChkScope* Scope;

    /// <summary>
    /// Глубина вложенности областей.
    /// </summary>
    public byte ScopeNesting;

    /// <summary>
    /// Результат проверки.
    /// </summary>
    public MdbxChkResultData Result;
}

/// <summary>
/// Данные результата проверки.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct MdbxChkResultData
{
    /// <summary>
    /// Общий объем полезной нагрузки в байтах.
    /// </summary>
    public nuint TotalPayloadBytes;

    /// <summary>
    /// Общее и обработанное количество таблиц.
    /// </summary>
    public nuint TableTotal, TableProcessed;

    /// <summary>
    /// Общее количество потерянных байт и страниц.
    /// </summary>
    public nuint TotalUnusedBytes, UnusedPages;

    /// <summary>
    /// Обработанные страницы, возвращаемые страницы, страницы GC,
    /// выделенные страницы, сопоставленные страницы.
    /// </summary>
    public nuint ProcessedPages, ReclaimablePages, GcPages, AllocPages, BackedPages;

    /// <summary>
    /// Проблемы: метаданные, дерево, GC, KV, общие.
    /// </summary>
    public nuint ProblemsMeta, TreeProblems, GcTreeProblems, KvTreeProblems, ProblemsGc, ProblemsKv, TotalProblems;

    /// <summary>
    /// ID транзакций.
    /// </summary>
    public ulong SteadyTxnid, RecentTxnid;

    /// <summary>
    /// Гистограмма возраста страниц.
    /// </summary>
    public MdbxChkHistogramData HistogramPageAge;

    /// <summary>
    /// Гистограмма pgno удерживаемого читателями.
    /// </summary>
    public MdbxChkHistogramData HistogramPgnoPayload;

    /// <summary>
    /// Гистограмма pgno, используемого всей полезной нагрузкой.
    /// </summary>
    public MdbxChkHistogramData HistogramPgnoRetained;

    /// <summary>
    /// Указатель на массив указателей на структуры MDBX_chk_table_t.
    /// </summary>
    public MdbxChkTable* Tables;
}

/// <summary>
/// Набор функций обратного вызова, используемых для проверки целостности базы данных.
/// </summary>
/// <remarks>
/// Соответствует структуре MDBX_chk_callbacks_t из заголовочного файла mdbx.h.
/// Все функции обратного вызова опциональны, неиспользуемые должны быть nullptr.
/// Содержит 16 полей-указателей на функции. 3 функции используют va_list,
/// поэтому для них используется void*.
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public unsafe struct MdbxChkCallbacks
{
    /// <summary>
    /// Функция проверки прерывания.
    /// </summary>
    public delegate* unmanaged[Cdecl]<MdbxChkContext*, bool> CheckBreak;

    /// <summary>
    /// Функция входа в область (использует va_list, поэтому void*).
    /// </summary>
    public void* ScopePush;

    /// <summary>
    /// Функция завершения области.
    /// </summary>
    public delegate* unmanaged[Cdecl]<MdbxChkContext*, MdbxChkScope*, MdbxChkScope*, int> ScopeConclude;

    /// <summary>
    /// Функция выхода из области.
    /// </summary>
    public delegate* unmanaged[Cdecl]<MdbxChkContext*, MdbxChkScope*, MdbxChkScope*, void> ScopePop;

    /// <summary>
    /// Функция обработки проблемы (использует va_list, поэтому void*).
    /// </summary>
    public void* Issue;

    /// <summary>
    /// Фильтр таблицы.
    /// </summary>
    public delegate* unmanaged[Cdecl]<MdbxChkContext*, MDBX_val*, uint, MdbxChkUserTableCookie*> TableFilter;

    /// <summary>
    /// Завершение таблицы.
    /// </summary>
    public delegate* unmanaged[Cdecl]<MdbxChkContext*, MdbxChkTable*, MDBX_cursor*, int> TableConclude;

    /// <summary>
    /// Освобождение таблицы.
    /// </summary>
    public delegate* unmanaged[Cdecl]<MdbxChkContext*, MdbxChkTable*, void> TableDispose;

    /// <summary>
    /// Обработка пары ключ-значение.
    /// </summary>
    public delegate* unmanaged[Cdecl]<MdbxChkContext*, MdbxChkTable*, nuint, MDBX_val*, MDBX_val*, int> TableHandleKv;

    /// <summary>
    /// Начало этапа.
    /// </summary>
    public delegate* unmanaged[Cdecl]<MdbxChkContext*, MdbxChkStage> StageBegin;

    /// <summary>
    /// Конец этапа.
    /// </summary>
    public delegate* unmanaged[Cdecl]<MdbxChkContext*, MdbxChkStage, int> StageEnd;

    /// <summary>
    /// Начало печати.
    /// </summary>
    public delegate* unmanaged[Cdecl]<MdbxChkContext*, MdbxChkSeverity, MdbxChkLine*> PrintBegin;

    /// <summary>
    /// Сброс печати.
    /// </summary>
    public delegate* unmanaged[Cdecl]<MdbxChkLine*, void> PrintFlush;

    /// <summary>
    /// Завершение печати.
    /// </summary>
    public delegate* unmanaged[Cdecl]<MdbxChkLine*, void> PrintDone;

    /// <summary>
    /// Печать символов.
    /// </summary>
    public delegate* unmanaged[Cdecl]<MdbxChkLine*, byte*, nuint, void> PrintChars;

    /// <summary>
    /// Печать форматированной строки (использует va_list, поэтому void*).
    /// </summary>
    public void* PrintFormat;

    /// <summary>
    /// Печать размера.
    /// </summary>
    public delegate* unmanaged[Cdecl]<MdbxChkLine*, byte*, ulong, byte*, void> PrintSize;
}
