<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>mdbx-dotnet</AssemblyName>
		<Authors>Jerry.Wang, Anton May</Authors>
		<PackageProjectUrl>https://public.amsoft.spb.ru/libmdbx</PackageProjectUrl>
		<PackageId>mdbx</PackageId>
		<Description>.NET bindings of libmdbx - Fastfull embedded transactional key-value storage engine. Surpasses the legendary LMDB in reliability, capabilities and performance.  Used in hundreds of open source projects, including Ethereum.</Description>
		<PackageTags>lmdb mdbx libmdbx key-value performance storage-engine no-sql</PackageTags>
		<Version>0.14.2.8-5-develop</Version>
		<PublishAot>true</PublishAot>
		<AssemblyTitle>mdbx-dotnet</AssemblyTitle>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<ErrorReport>none</ErrorReport>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
		<SignAssembly>False</SignAssembly>
		<Title>libmdbx-dotnet</Title>
		<Copyright>Jerry.Wang, Anton May</Copyright>
		<RepositoryUrl>https://public.git.amsoft.spb.ru/libmdbx/libmdbx-dotnet</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<Optimize>False</Optimize>
		<IsTrimmable>True</IsTrimmable>
		<IsAotCompatible>True</IsAotCompatible>
		<WarningLevel>9999</WarningLevel>
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
		<CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<IsTrimmable>True</IsTrimmable>
		<IsAotCompatible>True</IsAotCompatible>
		<WarningLevel>9999</WarningLevel>
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
		<CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
		<Optimize>False</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
		<None Update="native\windows\x64\*.dll" Pack="true" PackagePath="lib\net10.0">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="native\linux\x64\*.so" Pack="true" PackagePath="lib\net10.0">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Resources\LocalResources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>LocalResources.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resources\LocalResources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>LocalResources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

</Project>